tpope/vim-markdown

syntax/markdown.vim

I noticed that vim markdown wasn't treating escaped angle braces as escaped.  This change helps vim markdown syntax match escaped angle braces so they are not matched as html tag delimiters.
Escaped like \<b>this\</b> means it is _not_ an <b>html<b> tag.
Escaped like \<b>this\</b> means it is _not_ an <b>html</b> tag.

Add escape support for angle braces

---

syntax/markdown.vim

The current fenced code block matching does not support the syntax used by [Kramdown][1] or fully support the syntax described in [CommonMark][2].  The differences are:
* Kramdown requires \~ instead of \` in fences (CommonMark permits \~)
* Both permit code fences to have more than 3 \~ or \` characters
* Both require the closing fence to have as many chars as the opening
* Both permit the closing fence to have extra fence chars
* CommonMark explicitly forbids \` in the fence info string
This is likely the case with other Markdown variants, but these are the only two that I considered when authoring this PR.  If more Markdown implementation support is required, please let me know.
This commit implements all of the above mentioned changes.  The change is mostly straight-forward.  The only …

Improve fenced code block matching for Kramdown/CommonMark

---

syntax/markdown.vim

Example .vimrc:
let g:markdown_fenced_languages = ['vim', 'viml=vim']
syntax on
causes
"/tmp/test.mkd" 6L, 98C
Error detected while processing /usr/share/vim/vim74/syntax/vim.vim:
line  777:
E403: syntax sync: line continuations pattern specified twice
E403: syntax sync: line continuations pattern specified twice
Example "test.mkd" file:
```vim
echo 'hi'
```

Avoid E403 error on :syn-include

---

ftplugin/markdown.vim

I think it is more common to use `>` to signify block quotes instead of comments.

changed markdown comment string to use html style comment

---

README.markdown
syntax/markdown.vim

Adding a small option to turn off syntax concealing (similar to how [vim-json](https://github.com/elzr/vim-json) does it).

Allow toggling of syntax concealing.

---

syntax/markdown.vim

This closes #100, by allowing the `spell` option to spell check bold and italic text.

Fix spell check on bold and italic text

---

README.markdown
syntax/markdown.vim

Currently markdown (including Vim's standard `syntax/markdown.vim`) syntax highlight is synchronized with `syn sync minlines=10`.
However, it causes collapsed highlight at large code block on scrolling a buffer.
This is because the `minlines` config is too small to find the edge of fenced code.
I fixed this by making the `minlines` config customizable. If someone has trouble with collapsed highlight with large code block, customizing `g:markdown_minlines` will solve the problem.
I didn't change default value because of compatibility and performance in mind. (Some old PC may causes performance error when increase the value of `g:markdown_minlines`)
Ruby uses the same approach `g:ruby_minlines` because Ruby must also find the `... end` block.
I'd much appreciate if you contribute this …

Customizable minlines with g:markdown_minlines

---

ftplugin/markdown.vim

Adds a foldtext function, for which 'Bonus points' were offered in #10 😜
- Displays == and -- headers as # and ##
- Use markdown header style instead of '+--' to show nesting
Given the example:
This is Header One
==================
This is Header Two
-----------------
This is a normal line
Instead of:
+--  6 lines: This is Header One-----------------------------
+---  4 lines: This is Header Two----------------------------
+----  2 lines: ### This is Header Three---------------------
You get:

Markdown fold text function

---

README.markdown

Introduced in late 2014:
https://github.com/vim/vim/commit/7d76c804af900ba6dcc4b1e45373ccab3418c6b2#diff-44a099e40ae628aef90a28c6408a4c61R1154

readme: Upstream matches *.md to Markdown

---

syntax/markdown.vim

Conceals the start and end markers of code blocks.
Fixes #114 
Example:

Conceal code blocks

---

ftplugin/markdown.vim

Previously in Markdown files, Vim would treat heading syntax in code
fences as Markdown headers. This commit ensures that only headers will
be folded by checking the `synIDattr` of the item.
E.g. The comment in this code snippet would have been treated as a
Markdown header.
<pre>
```sh
echo "Hello world"
```
</pre>

Prevent the folding of heading syntax in code fences

---

syntax/markdown.vim

This supports fenced code attributes for pandoc style markdown (see [here](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes)).
In the example Markdown below, this will highlight the code block with bash syntax highlighting (assuming `g:markdown_fenced_languages` is set up properly).
````markdown
Code block:
``` {#my-code-block .numberLines .bash}
foo() {
bar="1"
echo $bar
}
```
````

Support pandoc syntax for fenced code blocks

---

syntax/markdown.vim

Github parses underscores not the same way as asterisks if they are inside _such_an_identifier_
Just look at this repo https://github.com/igrmk/github-markdown-corner-cases
This PR is adding support for such parsing
Asterisks are still parsed the old way
The feature is enabled only if `markdown_syntax_github` is set to 1

Github flavored parsing of underscores

---

ftplugin/markdown.vim

1. Add support for setext style headings
2. Use the 's' flag in `search()` to set the `'` mark instead of using `m'`
3. Fix the guard. Before, the maps would still be created if, e.g. `g:no_markdown_maps` was set but `g:no_plugin_maps` was unset. Likewise if `g:no_plugin_maps` was set but `g:no_markdown_maps` was unset. Only create the maps if _both_ `g:no_plugin_maps` and `g:no_markdown_maps` are unset.

Update [[ and ]] mappings

---

syntax/markdown.vim

According to the [CommonMark spec](https://spec.commonmark.org/0.29/#atx-headings), ATX headings must be followed by a space, i.e.
```markdown
```
```markdown
#this is not a heading
```
The spec also allows 1-3 leading spaces before a header:
```markdown
```
This updates the syntax file to match these requirements.

Update header pattern to include trailing space

---

ftplugin/markdown.vim

Previously, vim wouldn't recognise indented bulletpoints as being part of a list, and would mangle them when trying to wrap with <kbd>gq</kbd>.
Previously submitted as vim/vim#6848.
Possibly this should also remove `fb:*,fb:-,fb:+` from `comments`? (see #134)

Recognise indented bulleted lists for wrapping

---

syntax/markdown.vim

Addresses the sequel to issue #154.
See https://github.com/tpope/vim-markdown/issues/154#issuecomment-778677280

Don't let fenced languages change &foldtext

---

syntax/markdown.vim

If a line begins (ignoring any space characters) with a *word* that happens to match one of the languages listed in `g:markdown_fenced_languages`, the line is wrongly detected as being the start of a fenced code-block for that language.
As an example, the following line would be highlighted as the start of fenced code block and lines immediately following it are highlighted as SQL statements (until a blank line is reached).
> SQL (Structured Query Language) is a declarative language
This bug was introduced in the [most recent commit](https://github.com/tpope/vim-markdown/commit/296eeaa8877528fae45e89a9013c5a8d317deef1) where an extraneous asterisk allows for *zero* matches of the `\z(~\{3,\}\)` atom. This pull request should ensure that a line is only treated as the start of a fenced code …

Prevent false detection of fenced code block start

---

ftplugin/markdown.vim

Add the missing bar and setl command, which previously hadn't been
necessary until the addition of [[ and ]] maps.

Fix undo_ftplugin

---

syntax/markdown.vim

These patches modify the syntax rules for emphasis to
* prevent the emphasis delimiter from breaking the highlighting of the entire buffer, and
* follow the rules of more popular markdown variants.

Make emphasis syntax more robust & compliant

---

syntax/markdown.vim

As was requested in #26 and implemented in #34 (but with an unsatisfactory highlight group) I've taken the liberty to alter that PR to use a better highlight group instead.
(I've also had to adjust @therod's changes to fit into the current state of the syntax file.)

Adding strikethrough support via the `htmlStrike` highlight group
